### ISSUE TITLE
Proposal: Replace `Timber` and `Slimber` with `square/logcat`

### ISSUE THREAD

**Issue by oscarnylander** [HedvigInsurance/android#749]
Motivation: `Timber`+`Slimber` does more or less the same as `square/logcat` would do for us, but in a slightly more performant manner. We would also avoid the lint errors that we get from the current version of `Timber`+`Slimber` that we are using.

https://github.com/square/logcat

**Comment by hugokallstrom** [comment]
Lets do it :)

**Comment by StylianosGakis** [comment]
Looked into this a bit, there's one thing. We're currently using Timber as both local logs and for firebase by doing this
https://github.com/HedvigInsurance/android/blob/4b421e1e7673aa86ffe7b2e2581cb4204a1b8b83/app/src/main/java/com/hedvig/app/HedvigApplication.kt#L71-L75
logcat explicitly states in the documentation:
"One could setup a custom logger that send logs remotely in release builds, however we do not recommend doing so: in our experience, remote logs should be distinct in code from local logs and clearly identified as such, because the volume and performance impact should be very distinct."
and lives up to this recommendation by having its logger interface that we'd need to implement ourselves only take in a String
https://github.com/square/logcat/blob/f877f806e8dce98a3abbc2ca80e6447b38cd8f42/logcat/src/main/java/logcat/LogcatLogger.kt#L24-L28
no information about any Throwables which is what we're using in our current Timber implementation to properly log to Firebase.
https://github.com/HedvigInsurance/android/blob/4b421e1e7673aa86ffe7b2e2581cb4204a1b8b83/app/src/main/java/com/hedvig/app/util/FirebaseCrashlyticsLogExceptionTree.kt#L10-L17

So before we do this, we'd need to decide on wether we should start differentiating between logs that are interesting for Firebase compared to local logs, and if we want to do that start being explicit about what kind of log each log is. For that we could keep Timber for firebase reporting and logcat for dev-eyes only debug logging, or whatever else feels good.

Or of course make our own version of logcat's implementation which does actually take in a throwable, but at that point we're missing the point of the library and should keep using Timber anyway.

**Comment by StylianosGakis** [comment]
Slimber was just updated to 2.0 with this diff https://github.com/PaulWoitaschek/Slimber/compare/1.0.7...2.0.0 and I updated us here https://github.com/HedvigInsurance/android/pull/1284 meaning that we can just stick with that one for now.
I don't think we should be getting any lint errors with it, they improved the imports to be proper imports rather than just top level `e` and so on, so the experience is much nicer, and it's still using the same technique of passing the string inside the lambda aka not evaluating it unless needed. So I think there's no reason to move to logcat anyway for now, closing, open again if I missed something.
